import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
      <h1 className="text-2xl sm:text-3xl font-semibold text-gray-900">Terms of Service</h1>
      <p className="mt-4 text-gray-700 leading-relaxed">
        By using this site, you agree to use it lawfully and responsibly.
      </p>

      <section className="mt-6 space-y-3 text-gray-700 leading-relaxed">
        <p>
          The tools provide creative guidance only. Outputs are generated by AI and may be inaccurate, incomplete, or unsuitable for your purpose.
        </p>
        <p>
          You are responsible for how you use any suggestions, text, or ideas produced by the tools. Always apply your own judgement.
        </p>
        <p>
          We may update or withdraw features at any time and may revise these terms when needed.
        </p>
      </section>

      <p className="mt-8">
        <Link href="/" className="text-sm text-gray-600 hover:text-gray-900 hover:underline underline-offset-2">
          Back to home
        </Link>
      </p>
    </main>
  );
}
